### ISSUE TITLE
Unable to locate spawn_ur5_launch_moveit.launch.py 

### ISSUE THREAD

**Issue by Avisheet** [eYantra-Robotics-Competition/eyrc-24-25-logistic-cobot#3]
While running 'ros2 launch ur_simulation_gazebo spawn_ur5_launch_moveit.launch.py ', I am getting the error as :
file 'spawn_ur5_launch_moveit.launch.py' was not found in the share directory of package 'ur_simulation_gazebo' which is at '/home/<usr>/colcon_ws/install/ur_simulation_gazebo/share/ur_simulation_gazebo'. Even I'm unable to find this launch file in my workspace.

**Comment by JaisonJose241** [comment]
Do check the new commit.

**Comment by Siddharth2308** [comment]
Checkout to the latest release #2

**Comment by Avisheet** [comment]
Hey @Siddharth2308, I have pulled the latest release, then also it's unable to find spawn_ur5_launch_moveit.launch.py.What should I do regarding that? I am getting the same error as above after pulling and building the latest release.

**Comment by Siddharth2308** [comment]
Go through the [Moveit Gazebo Interface](https://portal.e-yantra.org/themeBook/lb/Task_1/learning_resources/arm_manipulation/moveit/moveit_gazebo_interface.html) Section in learning resources
