### ISSUE TITLE
spawn_ur5_launch_moveit.launch.py file not found

### ISSUE THREAD

**Issue by Omega-Nexus-arch** [eYantra-Robotics-Competition/eyrc-24-25-logistic-cobot#4]
file 'spawn_ur5_launch_moveit.launch.py' was not found in the share directory of package 'ur_simulation_gazebo' which is at '/home/anaay/workspaces/colcon_ws/install/ur_simulation_gazebo/share/ur_simulation_gazebo'

**Comment by Siddharth2308** [comment]
[Refer](https://github.com/eYantra-Robotics-Competition/eyrc-24-25-logistic-cobot/issues/3)
