### ISSUE TITLE
ebot_description not found error

### ISSUE THREAD

**Issue by AnkitHazarika** [eYantra-Robotics-Competition/eyrc-24-25-logistic-cobot#8]
Whenever I run the part:
    ros2 launch ebot_description ebot_gazebo_launch.py
The terminal gives the error saying:
Package 'ebot_description' not found: "package 'ebot_description' not found, searching: ['/opt/ros/humble']"

Tough I have the entire source file downloaded . It keeps saying this. I haven't pulled yet

**Comment by doctord00m** [comment]
to fix this, cd into your pulled eyrc folder. 
Then just try doing
`source install/local_setup.bash`
alternatively
`source install/setup.bash`
it should get fixed.
If you're using some other shell like `zsh` then just change the command to `install/setup.zsh` accordingly.

**Comment by doctord00m** [comment]
> to fix this, cd into your pulled eyrc folder. Then just try doing `source install/local_setup.bash` alternatively `source install/setup.bash` it should get fixed. If you're using some other shell like `zsh` then just change the command to `install/setup.zsh` accordingly.

This is assuming you have run `colcon build` of course. You can refer to this for better details.

https://portal.e-yantra.org/themeBook/lb/Task_0/learning_resources/ros_basics/ros_workspace.html
https://portal.e-yantra.org/themeBook/lb/Task_0/warehouse_setup_task/task_instruction.html

**Comment by AnkitHazarika** [comment]
Yes, I reinstalled everything and it is fixed now. Thank you
