### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by shanmugam754** [eYantra-Robotics-Competition/eyrc-24-25-logistic-cobot#9]
no module named moveit_commander

**Comment by JatinPatil2003** [comment]
Moveit_commander only exists for ROS1. ROS2 doesn't have moveit_commander

**Comment by Shan1234mugam** [comment]
> Moveit_commander only exists for ROS1. ROS2 doesn't have moveit_commander
I used moveit2.py the same error is shown
